apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sungboklimtestgit 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sungboklimtestgit 
    spec:
      containers:
        - name: sungboklimtestgit 
          image: mycontainertest001.azurecr.io/sungboklimtestgit
          ports:
          - containerPort: 8080